deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Checkout current repo
      uses: actions/checkout@v4

    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Clone target repo (bido-cyber.github.io)
      run: |
        git clone --depth=1 https://x-access-token:${{ secrets.GH_PAGES_TOKEN }}@github.com/bido-cyber/bido-cyber.github.io.git out
        rm -rf out/*
      env:
        GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

    - name: Copy build output
      run: cp -r dist/* out/

    - name: Commit and push to target repo
      run: |
        cd out
        git add .
        git commit -m "Deploy from main repo [skip ci]" || echo "No changes to commit"
        git push
